"use client";

import { useEffect, useRef, useState } from "react";
import { STATIONS } from "@/lib/stations";
import type { Anomaly, Tweaks } from "@/lib/types";
import { Station, type StationHandle } from "@/components/Station";
import { ArchivePanel } from "@/components/ArchivePanel";
import { TweaksPanel } from "@/components/TweaksPanel";

const STORAGE_KEY = "station-four-tweaks";
const ANOM_KEY = "station-four-anomalies";

function loadTweaks(): Tweaks {
  if (typeof window === "undefined") return { stationMode: "mixed", archiveMode: "feed", freq: "normal" };
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw);
  } catch {}
  return { stationMode: "mixed", archiveMode: "feed", freq: "normal" };
}

function loadAnomalies(): Anomaly[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(ANOM_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as Anomaly[];
    // keep only same-day entries to avoid cross-session drift
    const today = new Date().toISOString().slice(0, 10);
    return parsed.filter((a) => a.date === today).slice(0, 100);
  } catch {
    return [];
  }
}

export default function StationFourPage() {
  const [tweaks, setTweaks] = useState<Tweaks>(loadTweaks);
  const [anomalies, setAnomalies] = useState<Anomaly[]>(() => loadAnomalies());
  const [clock, setClock] = useState<string>("—");
  const stationRefs = useRef<Array<StationHandle | null>>([]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(tweaks));
  }, [tweaks]);

  useEffect(() => {
    try {
      localStorage.setItem(ANOM_KEY, JSON.stringify(anomalies.slice(0, 100)));
    } catch {}
  }, [anomalies]);

  useEffect(() => {
    const id = setInterval(() => {
      const d = new Date();
      const pad = (n: number) => String(n).padStart(2, "0");
      setClock(`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`);
    }, 1000);
    return () => clearInterval(id);
  }, []);

  const handleAnomaly = (ev: Anomaly) => {
    setAnomalies((prev) => [ev, ...prev].slice(0, 100));
  };

  const handleReplay = (ev: Anomaly) => {
    const idx = STATIONS.findIndex((s) => s.id === ev.cam);
    if (idx >= 0) {
      stationRefs.current[idx]?.replayAnomaly(ev);
    }
  };

  const handleTriggerRandom = () => {
    const candidates = stationRefs.current.filter(Boolean);
    if (!candidates.length) return;
    const pick = candidates[Math.floor(Math.random() * candidates.length)];
    pick?.triggerGlitch();
  };

  return (
    <div className="shell">
      <div className="main">
        <header className="top">
          <div>
            <h1>
              Station Four · <em>live testbed</em>
            </h1>
            <div className="sub">
              Four live feeds, running as normal. Motion and <em>Gemini Vision</em> together trigger a{" "}
              <em>transformation event</em> — a 4–6 second hallucination, archived, and the feed returns. Each station
              argues for a different <em>mode</em> of mythology. The archive panel (right) shows captured anomalies in
              whichever <em>mode</em> you select.
            </div>
          </div>
          <div className="meta">
            EST. 2026 · SYNDICATE FEED
            <br />
            <span>{clock}</span>
            <br />
            <span>{String(anomalies.length).padStart(3, "0")}</span> ANOMALIES TODAY
          </div>
        </header>

        <div className="grid">
          {STATIONS.map((s, i) => (
            <Station
              key={s.id}
              ref={(el) => {
                stationRefs.current[i] = el;
              }}
              station={s}
              tweaks={tweaks}
              onAnomaly={handleAnomaly}
            />
          ))}
        </div>

        <div className="note-source">
          <b>LIVE SOURCES</b>
          <br />
          Wolf: <code>International Wolf Center · Ely MN</code> (explore.org / YouTube).
          Deer: <code>Transylvania Wilds · Romania</code>.
          Bird: <code>Cornell Lab FeederWatch · Sapsucker Woods 4K</code>.
          Polar: <code>Wapusk National Park · Cape South</code>.
          Streams are pulled via a server-side HLS proxy and played through hls.js into a canvas so Gemini Vision can
          analyse frames without CORS trouble. If a source drops, each station falls back to a synthetic animated
          background and the AI pipeline continues to run on what remains visible. Mythology lines, glitch transcripts,
          and delirium labels are generated by <code>gemini-2.0-flash</code>.
        </div>
      </div>

      <ArchivePanel anomalies={anomalies} tweaks={tweaks} onReplay={handleReplay} />

      <TweaksPanel tweaks={tweaks} onChange={setTweaks} onTriggerRandom={handleTriggerRandom} />
    </div>
  );
}
